### ISSUE TITLE
Wrong Log Level when writing json file

### ISSUE THREAD

**Issue by serinth** [pact-foundation/pact-go#10]
Running on Mac OS the Pact daemon with no arguments we get this output:
```
2017/02/09 15:33:14 [ERROR] 
2017/02/09 15:33:14 [ERROR] Writing pact for <SERVICE> to /Users/<OMITTED>/go/src/<FILE>.json
```
I've replaced some sensitive info with <OMITTED>, <SERVICE> and <FILE>.
The json file gets written properly so functionally it's fine. The `[ERROR]` is probably just the wrong log level.

**Comment by mefellows** [comment]
Unfortunately this is just how the underlying Ruby process works, it was certainly confusing to me at first (also requiring some coding gymnastics to interpret _actual_ errors!). This seems to be a common thing in other Pact implementations also (at least in Java). I'll ask some others in the Pact community to get a better understanding.

**Comment by bethesque** [comment]
I don't think it's the ruby. Here's the code.

https://github.com/pact-foundation/pact-mock_service/blob/master/lib/pact/mock_service/app.rb#L49
```ruby
def write_pact_if_configured
        consumer_contract_writer = ConsumerContractWriter.new(@session.consumer_contract_details, StdoutLogger.new)
        consumer_contract_writer.write if consumer_contract_writer.can_write?
      end

    # Can't write to a file in a TRAP, might deadlock
    class StdoutLogger
      def info message
        $stdout.puts "\n#{message}"
      end
    end
  end
```

https://github.com/pact-foundation/pact-mock_service/blob/master/lib/pact/consumer_contract/consumer_contract_writer.rb#L56
```ruby
def update_pactfile
      logger.info log_message

      ...
    end

    def log_message
      if updating?
        "Updating pact for #{provider_name} at #{pactfile_path}"
      else
        "Writing pact for #{provider_name} to #{pactfile_path}"
      end
    end
```

**Comment by mefellows** [comment]
Thanks Beth, I'm digging into this again just now.

**Comment by mefellows** [comment]
That fix now does imply that we get an `ERROR` when the Ruby process shuts down (WEBrick seems to write to stderror) but it fixes the problem - simple mistake, sorry team!
