### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by AlexRamey** [pact-foundation/pact-go#103]
Curious about when v1.0.0 will be released?

Also, for the newer 1.0 beta versions, can we still get the links to platform-specific builds?

![screen shot 2018-12-06 at 11 54 30 am](https://user-images.githubusercontent.com/6226193/49598956-c3f1c580-f94d-11e8-96b4-e0088296c2bf.png)

They are very convenient for pulling this stuff down in CI.

UPDATE: I've updated our project to the latest `1.0.0-beta.3` and now see that the recommended approach for starting the daemon is to use the standalone tool. Given that, there is no need to include those links anymore. Now I'm just wondering about when to expect v1.0.0!

**Comment by mefellows** [comment]
Release coming soon - there is one last couple of things to get in and then officially launch. I understand people aren't always happy seeing a "beta" in their deps!

**Comment by nenad** [comment]
Tag is there now, I suppose release coming very soon? :tada:

**Comment by mefellows** [comment]
Ha, it is indeed. I'm not sure we actually need a release (assuming you mean GitHub release), given that it is go-gettable. Can you you help me understand why we should keep that process going?

**Comment by mefellows** [comment]
I should note, that the release does get created (see below). The [changelog](https://github.com/pact-foundation/pact-go/blob/master/CHANGELOG.md) is updated also. It's just that it hasn't propagated to the release page (doable just not yet automated). 

<img width="1092" alt="Screen Shot 2019-10-21 at 11 36 19 am" src="https://user-images.githubusercontent.com/53900/67169451-14073880-f3f7-11e9-800f-3346328bff38.png">
