### ISSUE TITLE
Tests time out waiting for daemon.

### ISSUE THREAD

**Issue by tutabeier** [pact-foundation/pact-go#107]
## Software versions

* **OS**: e.g. Mac OSX 10.14.1
* **Consumer Pact library**: Pact JS 7.2
* **Provider Pact library**: Pact-Go 0.0.13
* **Golang Version**: `go1.11.4 darwin/amd64`
* **Golang environment**:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/lbeier/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/lbeier/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/y7/d9mxr9110j79f3c_gj1jm2qr0000gn/T/go-build294272329=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

## Expected behaviour
The tests should start the server and validate the provider using Pact Broker.

## Actual behaviour
The server starts, but the tests time out waiting for Deamon on port 0.
```
--- FAIL: TestPact (10.13s)
    pact.go:270: Error: Expected server to start < 10s. Timed out waiting for Daemon on port 0 - are you
        		sure it's running?
FAIL
```

## Steps to reproduce
The code is here:
https://github.com/tutabeier/pact-consumer-provider/blob/master/provider/cmd/provider/main_test.go

Consider forking the project and modifying the [E2E test](https://github.com/pact-foundation/pact-go/blob/master/dsl/pact_integration_test.go)
I couldn't find the `pact_integration_test.go` file.

## Relevent log files
This is the log for the test I mentioned above:
```
=== RUN   TestPact
[GIN-debug] [WARNING] Now Gin requires Go 1.6 or later and Go 1.7 will be required soon.

[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /users                    --> github.com/tutabeier/pact-consumer-provider/provider/cmd/provider.usersHandler (3 handlers)
[GIN-debug] POST   /setup                    --> github.com/tutabeier/pact-consumer-provider/provider/cmd/provider.startServer.func1 (3 handlers)
[GIN-debug] Listening and serving HTTP on :7777
[DEBUG] pacts to verify:  map[http://127.0.0.1:3000/pacts/provider/api-in-go/consumer/frontend-client/version/2.0.0:http://127.0.0.1:3000/pacts/provider/api-in-go/consumer/frontend-client/version/2.0.0]
--- FAIL: TestPact (10.13s)
    pact.go:270: Error: Expected server to start < 10s. Timed out waiting for Daemon on port 0 - are you
        		sure it's running?
FAIL

Process finished with exit code 1
```

**Comment by mefellows** [comment]
Thanks for sharing a repository where I can recreate the issue.

I've just downloaded it and published it to a test account on our [hosted broker](https://pact.dius.com.au)

`publishtoBrocker.js`:
```js
let opts = {
  providerBaseUrl: 'http://127.0.0.1:8989',
  pactFilesOrDirs: [path.resolve(process.cwd(), 'pacts')],
  pactBroker: 'https://test.pact.dius.com.au',
  pactBrokerUsername: 'dXfltyFMgNOFZAxr8io9wJ37iUpY42M',
  pactBrokerPassword: 'O5AIZWxelWbLvqMd8PkAVycBJh2Psyg1',
  consumerVersion: revision = require('child_process').execSync('git rev-parse HEAD').toString().trim()
}
```

`main_test.go`:
```go
	pactBrokerHost     = "https://test.pact.dius.com.au"
	pactBrokerUsername = "dXfltyFMgNOFZAxr8io9wJ37iUpY42M"
	pactBrokerPassword = "O5AIZWxelWbLvqMd8PkAVycBJh2Psyg1"
```

The tests seem to pass OK:

<img width="1439" alt="screenshot" src="https://user-images.githubusercontent.com/53900/51008799-6d595600-15a1-11e9-9f8f-a098dab324b3.png">


Can you please test without `DisableToolValidityCheck: true`?

**Comment by tutabeier** [comment]
I was able to successfully run the tests using `v1.0.0-beta.3`, but no with `0.0.13`.

With the `0.0.13` it still fails:
```
--- FAIL: TestPact (10.17s)
    pact.go:270: Error: Expected server to start < 10s. Timed out waiting for Daemon on port 0 - are you
        		sure it's running?
FAIL
```

Since it works for me for the new version, I'm fine with it.

**Comment by mefellows** [comment]
Good to hear.

FWIW, the `0.0.x` release line required a separate install process documented [here](https://github.com/pact-foundation/pact-go/tree/release/0.x.x) and noted in the [readme](https://github.com/pact-foundation/pact-go#versions)
