### ISSUE TITLE
Intermittent failure when connecting to Pact Daemon

### ISSUE THREAD

**Issue by serinth** [pact-foundation/pact-go#11]
It looks like sometimes we get test failures when connecting to the Pact Daemon/Mock service it provides. This is inconsistent when running the tests. It can fail a bunch of times and then pass. 
This can cause CI to fail.

See below for sample output.
I've replaced the username with <USER>.
```
=== RUN   TestRule_Exists
2017/02/09 15:48:10 Error on Verify: Post http://localhost:61841/interactions: dial tcp [::1]:61841: getsockopt: connection refused
exit status 1
FAIL    consumer    1.074s

<USER>-rMBP:consumer <USER>$ go test -v
=== RUN   TestRule_Exists
--- PASS: TestRule_Exists (0.44s)
=== RUN   TestRule_DoesNotExists
--- PASS: TestRule_DoesNotExists (0.01s)
PASS
ok      consumer    0.983s
```

**Comment by mefellows** [comment]
This on a mac?

**Comment by serinth** [comment]
Yes, running on Mac OS X El Capitan.

**Comment by mefellows** [comment]
Could you please try the following and record the output during a failed run:

* start daemon with DEBUG and verbose logging:  `pact-go daemon -l DEBUG -v` 
* start the client with DEBUG logging e.g. `dsl.Pact{LogLevel: "DEBUG"}`

(please include all of the successful ones before hand also)

**Comment by mefellows** [comment]
OK got a random repro this morning. I'm guessing it's a race condition with the Mock Service. It reports up but the port not yet available.

Should be an easy enough fix in `daemon.StartServer` to wait for the port to become available.

**Comment by mefellows** [comment]
Have been able to reliably repro under load (using [stress](http://people.seas.harvard.edu/~apw/stress/))

Here's a run:
```
matt ~/go/src/github.com/pact-foundation/pact-go λ go run examples/consumer.go
2017/02/21 19:02:27 [DEBUG] pact setup logging
2017/02/21 19:02:27 [DEBUG] pact setup
2017/02/21 19:02:27 [DEBUG] client: starting a server
2017/02/21 19:02:27 [DEBUG] creating an HTTP client
2017/02/21 19:02:27 [DEBUG] waiting for port 6666 to become available
2017/02/21 19:02:28 [DEBUG] waiting for port 52458 to become available
2017/02/21 19:02:29 [ERROR] Expected server to start < 1s. Timed out waiting for Mock Server to
			start on port 52458 - are you sure it's running?
2017/02/21 19:02:29 [DEBUG] pact add interaction
2017/02/21 19:02:29 [DEBUG] pact setup logging
2017/02/21 19:02:29 [DEBUG] pact setup
2017/02/21 19:02:29 [DEBUG] pact add interaction
2017/02/21 19:02:29 [DEBUG] pact setup logging
2017/02/21 19:02:29 [DEBUG] pact setup
2017/02/21 19:02:29 [DEBUG] pact verify
2017/02/21 19:02:29 [DEBUG] mock service add interaction
2017/02/21 19:02:29 Error on Verify: Post http://localhost:52458/interactions: dial tcp [::1]:52458: getsockopt: connection refused
exit status 1
```

The timeout is just too small (1s) and additionally, the test should fail earlier (as you can see from the log). I'll bump this to 10 temporarily, and consider making this configurable (it's unlikely to be part of an end-state API so hesitant to add it in at this point).

**Comment by mefellows** [comment]
I've pushed a package that I've tested on a local Windows VM (Windows 11, 64bit).

Could you please check it out? (v0.0.3)

**Comment by mefellows** [comment]
Feedback from @serinth via direct email seems to confirm this is now fixed.

**Comment by mefellows** [comment]
Update, just waiting on a release before closing this off fully.
