### ISSUE TITLE
Feature request: Support message metadata verification on provider side

### ISSUE THREAD

**Issue by skaggmannen** [pact-foundation/pact-go#112]
## Software versions

* **OS**: Ubuntu 19.04
* **Consumer Pact library**: Pact go v1.0.0-beta.3
* **Provider Pact library**: Pact go v1.0.0-beta.3
* **Golang Version**:  1.12.1

## Expected behaviour

It should be possible to verify message metadata (such as topic names for MQTT) on the provider side. 

This is supported in e.g. `pact-jvm` from 3.6.5 (https://github.com/DiUS/pact-jvm/issues/479#issuecomment-485226710).

## Actual behaviour

It's not possible to verify message metadata.

**Comment by pavithra76** [comment]
Any update on this?

**Comment by mefellows** [comment]
This is scheduled for v3, however not yet currently supported in v2 matching and the underlying Ruby. Will use this ticket to log progress.

**Comment by mefellows** [comment]
Supported in 2.x.x, closing.
