### ISSUE TITLE
CustomProviderHeaders

### ISSUE THREAD

**Issue by alexeits** [pact-foundation/pact-go#113]
Are `CustomProviderHeaders` still supported? They stopped working after upgrade to beta5 (haven't upgraded in a year).

**Comment by mefellows** [comment]
No, they should definitely still be supported (albeit [`RequestFilter`s](https://github.com/pact-foundation/pact-go#request-filtering) are more powerful).

I'll double check, I upgraded the pact standalone last week so unless something has changed there...

**Comment by alexeits** [comment]
It doesn't appear that `CustomProviderHeaders` are being passed to the pact client:
https://github.com/pact-foundation/pact-go/blob/93caeeb9f84d67a8c129cd70e3e5958e21d8f952/dsl/pact.go#L350-L361

**Comment by mefellows** [comment]
Oh dear, thanks @alexeits good pickup. This was obviously omitted when wrapping the verification process for the new hooks API. 

I've pushed out a minor change now (beta-6) but will review with fresh eyes a bit later today to see if anything else is missing. Will also add a runnable example to prevent regressions.

**Comment by mefellows** [comment]
Have just added a regression example that covers this use case. Will push out a release tis week after some feedback on other requests/issues.
