### ISSUE TITLE
Pact broker version constraint

### ISSUE THREAD

**Issue by tomasbasham** [pact-foundation/pact-go#114]
Are there any technical reasons why later versions of the `pact_broker` are unsupported. I am pretty much forced to include the `DisableToolValidityCheck` because the broker version range has an upper limit of 2.0.0 (non-inclusive). The latest version is 2.34.0 (June 14, 2019) whilst the latest acceptable (1.18.0) version was released May 09, 2017. Should this be updated?

https://github.com/pact-foundation/pact-go/blob/b5a493b9157808d187d372288d092cfef9cec25f/install/installer.go#L22

**Comment by mefellows** [comment]
Probably just needs an update, will sort it out tomorrow

**Comment by mefellows** [comment]
New release out - enjoy and thanks for raising!
