### ISSUE TITLE
Can't run provider test with latest Pact CLI following the README

### ISSUE THREAD

**Issue by liul85** [pact-foundation/pact-go#115]
I installed the latest Pact CLI as described in the README, and try to run the provicer test sample, but failed with version [ERROR] CLI tools outdated.

if this is a constrain of the version compatibility I think the README may need to be updated.

## Software versions

* **OS**: Fedora 30
* **Consumer Pact library**: pact-go v1.0.0-beta.2
* **Provider Pact library**: pact-go v1.0.0-beta.2
* **Golang Version**: `1.12.7`
* **Golang environment**: Provide output of `go env`
* **Pact CLI Version**: `pact-1.69.0`
* **pact-broker Version**: `1.19.0`
* **pact-mock-service Version**: `3.1.1`
```
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/liangliu/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/liangliu/.gvm/pkgsets/go1.12.7/global"
GOPROXY=""
GORACE=""
GOROOT="/home/liangliu/.gvm/gos/go1.12.7"
GOTMPDIR=""
GOTOOLDIR="/home/liangliu/.gvm/gos/go1.12.7/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/liangliu/Learning/pact/pact-go-demo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build567655585=/tmp/go-build -gno-record-gcc-switches"
```

## Expected behaviour
test can run normally

## Actual behaviour
```
=== RUN   TestProvider
2019/07/27 22:06:59 [INFO] checking pact-broker within range >= 1.16.0, < 2.0.0
2019/07/27 22:07:00 [INFO] checking pact-mock-service within range >= 2.9.8, < 3.0.0
2019/07/27 22:07:01 [ERROR] CLI tools are out of date, please upgrade before continuing
FAIL	github.com/liul85/pact-go-demo	1.417s
```

## Steps to reproduce

the sample provider test case [here](https://github.com/pact-foundation/pact-go/blob/master/examples/provider_test.go)

## Relevent log files

N/A

![image](https://user-images.githubusercontent.com/1312723/61995601-438afb00-b0bd-11e9-8dc5-e78e02ff4f16.png)

**Comment by tomasbasham** [comment]
I have had similar issues with this package. To resolve it I installed https://github.com/pact-foundation/pact-ruby-standalone/releases which IMO is preferable than using `gem install pact`, so that your go project does not depend on configuring and maintaining a `Gemfile` and thus needing Ruby to be installed on the system.

**Comment by liul85** [comment]
> I have had similar issues with this package. To resolve it I installed https://github.com/pact-foundation/pact-ruby-standalone/releases which IMO is preferable than using `gem install pact`, so that your go project does not depend on configuring and maintaining a `Gemfile` and thus needing Ruby to be installed on the system.
> 
> Perhaps this should go in the README

Yeah, I install the CLI tools from this release page as well, actually you can't go with the latest version, you need to install the version as it showed from the test output, 
```
2019/07/27 22:06:59 [INFO] checking pact-broker within range >= 1.16.0, < 2.0.0
2019/07/27 22:07:00 [INFO] checking pact-mock-service within range >= 2.9.8, < 3.0.0
2019/07/27 22:07:01 [ERROR] CLI tools are out of date, please upgrade before continuing
```

this part definitely should be in the README

**Comment by mefellows** [comment]
Sorry for any confusion. But I'm confused - do we say anywhere that you must install using Gem? We say download the binaries and place on the PATH:

![screenshot](https://user-images.githubusercontent.com/53900/63141754-3ad97500-c02a-11e9-81f1-138df66a9823.png)

I'll check the version compatibility today and loosen future constraints where possible.

**Comment by mefellows** [comment]
Closing this as the current version supports the latest dependencies.

In case it wasn't clear, there is a `pact-go install` tool you can run to check this outside of a test:

![Screen Shot 2019-08-17 at 10 33 02 pm](https://user-images.githubusercontent.com/53900/63211764-01def480-c13f-11e9-84e2-8b8da7669c28.png)
