### ISSUE TITLE
It's not possible to do matrix based provider verification

### ISSUE THREAD

**Issue by mellowplace** [pact-foundation/pact-go#116]
To test all the production consumers against your provider changes, you typically want to do this kind of thing...

```
request := types.VerifyRequest{
		ProviderBaseURL:            "http://localhost:8000",
		ProviderVersion:            "0.0.1-" + os.Getenv("GIT_COMMIT"),
		PublishVerificationResults: publishPact,
		ProviderStatesSetupURL:     "http://localhost:8000/setup",
		CustomProviderHeaders:      []string{"Authorization: basic e5e5e5e5e5e5e5"},
		Provider: "MyProvider",
		Tags: string{"prod"},
}
```
But `Tags` and `Provider` don't seem to do anything?  Glancing at the code it looks like they're not wired up to actually produce arguments for the `pact-provider-verifier` command?  I'm using 1.0.0-beta.7 but this is the case in master also.

**Comment by mellowplace** [comment]
I think this is the fix...

https://github.com/pact-foundation/pact-go/pull/117

**Comment by mefellows** [comment]
Merged, closing. Release to go out later today.
