### ISSUE TITLE
v1.0.3 Build fails 

### ISSUE THREAD

**Issue by taboularasa** [pact-foundation/pact-go#121]
## Software versions

* **OS**: e.g. Mac OSX 10.14.6
* **Consumer Pact library**: e.g. Pact go v1.0.3
* **Golang Version**: go1.12.7 darwin/amd64

## Expected behaviour

successful build

## Actual behaviour

failed to build

https://github.com/pact-foundation/pact-go/commit/94da099cb51895646666443f20abc4410d77febf#diff-2a840891922e12f5e3573f1d11373d6eR64 includes a reference to the `os` package but does not include the import statement. 

## Steps to reproduce

build package

## Relevent log files

`github.com/pact-foundation/pact-go/dsl/publish.go:64:14: undefined: os`

**Comment by mefellows** [comment]
OK so there was a check for an exit code of `1` during in our `test.sh` script - but the test was failing with exit code `2`! I've fixed this, and confirmed that a broken test (which in this case we had) would fail the build.

`1.0.4` out the door.

**Comment by taboularasa** [comment]
Thank you!
