### ISSUE TITLE
Missing error check leads to nil pointer panic

### ISSUE THREAD

**Issue by Hades32** [pact-foundation/pact-go#126]
In some cases the `RoundTrip` call returns an error (e.g. `EOF`) and res is therefore `nil`:

https://github.com/pact-foundation/pact-go/blob/9fa77068bd49724a0fe38004586892206fb48e7e/proxy/http.go#L140

**Comment by mefellows** [comment]
Thanks for this, I noticed this recently when testing against a bad SSL certificate. 

I hit a wall with travis yesterday with a strange bug and haven't gotten back to the code - i'll add this as a fix though.

**Comment by mefellows** [comment]
This was closed by fa558a6.
