### ISSUE TITLE
Correct JSON failing matching

### ISSUE THREAD

**Issue by liamawhite** [pact-foundation/pact-go#15]
Getting error when trying to match logically accurate JSON probably due to formatting issues with and without the formatJSON function used in the examples. If it was explicit string matching then I would expect this behavior but not for flexible matching.

```	  
1) Verifying a pact between service-one and service-two Given User traffic exists for the current month A request for all traffic for the current month with GET /v1/traffic/usage/json returns a response which has a matching body
		     Failure/Error: expect(response_body).to match_term expected_response_body, diff_options
		       Actual: [{"org":"a6df0d8e-916b-4998-ac6e-149b299e2c9f","usage":12345}]
		       
		       @@ -1,7 +1,2 @@
		       -[
		       -  {
		       -    "org": "a6df0d8e-916b-4998-ac6e-149b299e2c9f",
		       -    "usage": 12345
		       -  },
		       -]
		       +[{"org":"a6df0d8e-916b-4998-ac6e-149b299e2c9f","usage":12345}]
		       
		       Key: - means "expected, but was not found". 
		            + means "actual, should not be found". 
		            Values where the expected matches the actual are not shown.
		     # /usr/local/bin/pact-provider-verifier/lib/app/pact-provider-verifier.rb:3:in `<main>'
		
		Finished in 0.0183 seconds
		2 examples, 1 failure
```

This is the printed output of my expected with pact matching terminology in it:

```
		{
		  "json_class": "Pact::ArrayLike",
		  "contents": {"org":
		{
			"json_class": "Pact::Term",
			"data": {
			  "generate": "a6df0d8e-916b-4998-ac6e-149b299e2c9f",
			  "matcher": {
			    "json_class": "Regexp",
			    "o": 0,
			    "s": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
			  }
			}
		},"usage":
		{
		  "json_class": "Pact::SomethingLike",
		  "contents": 12345
		}},
		  "min": 1
		}
```

**Comment by mefellows** [comment]
Can you please double check what `Content-Type` header you are sending is? This is usually the symptom of not setting the header correctly (the underlying validation library assumes text/plain, I believe).

**Comment by mefellows** [comment]
`formatJSON` should not be necessary, from memory they are in the examples for readability. It can probably go actually because it's not important for the example and makes things messy.

**Comment by liamawhite** [comment]
@mefellows awesome, that fixed it. Might be worth including a note in the docs about this?

**Comment by mefellows** [comment]
Will do - glad to hear that fixed it!

**Comment by mefellows** [comment]
Added "Troubleshooting" section, citing this example: https://github.com/pact-foundation/pact-go/wiki/Troubleshooting
