### ISSUE TITLE
PactLogDir ignored in types.VerifyRequest

### ISSUE THREAD

**Issue by SergeyRadist** [pact-foundation/pact-go#156]
## Software versions

* **OS**: e.g. Mac OSX 10.11.5
* **Consumer Pact library**: e.g. Pact go v1.5.1
* **Provider Pact library**: e.g. pact-jvm-provider-maven_2.11 v 3.3.8
* **Golang Version**: `go version`
* **Golang environment**: Provide output of `go env`

## Expected behaviour

```
	_, err := pact.VerifyProvider(t, types.VerifyRequest{
		PactLogDir: "/tmp/logs",
		PactLogLevel: "INFO",
	})
```
will cause writing logs in /tmp/logs with info level
## Actual behaviour

logs written in default path

## Steps to reproduce

use  types.VerifyRequest

**Comment by SergeyRadist** [comment]
Could I make pr ?

**Comment by mefellows** [comment]
Ah, good spot. Just added the fix now and pushed to master.
