### ISSUE TITLE
Generated pact file does not abide by the pact specification concerning the 'provider_state' field

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-go#16]
The generated pact files using pact-go differs from the ones generated with pact for java. Pact Go outputs 'provider_state' and for the java pact it outputs 'providerState'. According to the v2 of the pact specification it should be 'providerState'. This is due to the implementation coping the Ruby one.

Need to change 'provider_state' to 'providerState' at https://github.com/pact-foundation/pact-go/blob/master/dsl/interaction.go#L20

See https://github.com/pact-foundation/pact-js/issues/34

**Comment by bethesque** [comment]
👍

**Comment by mefellows** [comment]
I can update  send provider state _in_ (via the HTTP interface) as `providerState` - this is easy, the probably I'm seeing is that when we use the Mock Service (which I think uses this Gem to do it), it generates a pact file with `provider_state`. This is the real problem as it may cause interop issues.

**Comment by bethesque** [comment]
As mentioned in other thread, ruby mock service is embarrassingly incorrect. I'm updating it to providerState.

**Comment by bethesque** [comment]
Ruby code is updated to use camel case in the pacts in pact-mock_service 2.1.0. It has accepted both provider_state and providerState since almost forever, so we shouldn't have any upgrade problems.

**Comment by mefellows** [comment]
Closed by 9002469b0319f47e414cb4900731413b334712a8.
