### ISSUE TITLE
Dead link in docs

### ISSUE THREAD

**Issue by dabfleming** [pact-foundation/pact-go#163]
https://github.com/pact-foundation/pact-go/blob/eb10d18029ed05894fc2c9319f93ea1dea961a89/types/verify_request.go#L30

The above line suggests `https://docs.pact.io/selectors` for more info, which returns a 404.

Content seems to be at `https://docs.pact.io/pact_broker/advanced_topics/consumer_version_selectors/`

**Comment by mefellows** [comment]
I've fixed in on the docs.pact.io site - thanks for raising!
