### ISSUE TITLE
v2.x.x : Rust library installer fails on Github Action (Ubuntu 20.04)

### ISSUE THREAD

**Issue by raoulk** [pact-foundation/pact-go#171]
## Software versions

* **OS**: ubuntu-20.04 (in Github Action)
* **Golang Version**: `go1.16.5 linux/amd64`

## Expected behaviour

Rust FFI libraries installed with `go run github.com/pact-foundation/pact-go/v2 -l DEBUG install` work in provider test

(The installer works on my Macbook Pro, macOS 11.4) 

## Actual behaviour

Provider tests fails

## Logs from Github Action

```bash

# installation seems to work

go run github.com/pact-foundation/pact-go/v2 -l DEBUG install
2021/07/08 07:30:48 [INFO] package libpact_verifier_ffi not found
2021/07/08 07:30:48 [INFO] downloading library from pact-foundation/pact-reference@pact_verifier_ffi-v0.0.4 libpact_verifier_ffi-linux-x86_64.so.gz (download) to /usr/local/lib/libpact_verifier_ffi.so
2021/07/08 07:30:48 [INFO] downloading library from pact-foundation/pact-reference@libpact_mock_server_ffi-v0.0.17 libpact_mock_server_ffi-linux-x86_64.so.gz (download) to /usr/local/lib/libpact_mock_server_ffi.so
2021/07/08 07:30:49 [INFO] package libpact_verifier_ffi found
2021/07/08 07:30:49 [DEBUG] unable to determine current version of package pact_verifier_ffi this is probably because the package is currently being installed
2021/07/08 07:30:49 [INFO] package libpact_mock_server_ffi found
2021/07/08 07:30:49 [DEBUG] unable to determine current version of package libpact_mock_server_ffi this is probably because the package is currently being installed

# but is seems that something is missing

go test -p 1 -run HTTPProvider -tags=cdc -v ./cdc/...
# github.com/pact-foundation/pact-go/v2/internal/native/mockserver
/usr/bin/ld: cannot find -lpact_mock_server_ffi
collect2: error: ld returned 1 exit status
# github.com/pact-foundation/pact-go/v2/internal/native/verifier
/usr/bin/ld: cannot find -lpact_verifier_ffi
collect2: error: ld returned 1 exit status
```

**Comment by mefellows** [comment]
That would indicate it perhaps couldn't add the file to the correct path. I recall that sir perhaps not being writable, it is configurable via an ENV car tho.

Have a look at the GH Action setup for the v2.x.x branch to see how it does it.

No doubt it could do with improving so will leave this open to track.

I'm not in front of a computer right now but will look later.

**Comment by mefellows** [comment]
See also https://github.com/pactflow/terraform-provider-pact/blob/master/.github/workflows/test.yml

**Comment by raoulk** [comment]
Thanks, I will have a look!

**Comment by raoulk** [comment]
Adding the ENV block worked.  But I had to add one more command to my GH Action:
`sudo ldconfig # make Ubuntu aware of the new LD_LIBRARY_PATH`

```yaml
...
      - name: Run Consumer Driven Contract tests
        run: |
          sudo ldconfig
          run github.com/pact-foundation/pact-go/v2 -l DEBUG install 
          make cdc-test
...
```

**Comment by mefellows** [comment]
Strange, I'm using ubuntu latest https://github.com/pactflow/terraform-provider-pact/blob/master/.github/workflows/test.yml#L5 and didn't need to do that.

I'll leave this open, because it seems like either the installer isn't erroring out for a non-writable directory, or something else is going on.

**Comment by raoulk** [comment]
We have a pinned `runs-on: ubuntu-20.04` version.
If I switch to `ubuntu-latest`, it works without `sudo ldconfig`

Disclaimer: I'm not a Ubuntu expert, I don't know what was changed since `ubuntu-20.04`

**Comment by mefellows** [comment]
Thanks, that's helpful to know.

All working now, though?

**Comment by raoulk** [comment]
Yes, thanks for your help!

**Comment by mefellows** [comment]
Thanks. Also, i'm really keen for feedback on the v2.x.x branch. If you haven't already, please joins our [slack workspace](slack.pact.io] and say hello in #pact-go. I would really appreciate it.

**Comment by YOU54F** [comment]
Closing as looks like this is resolved, hope you are still using pact-go v2 and thanks for the feedback!
