### ISSUE TITLE
go get failure when importing the 2.x branch

### ISSUE THREAD

**Issue by pcting** [pact-foundation/pact-go#181]
## Software versions

* **OS**: Ubuntu 20.04.3 LTS, Linux 5.9.0-050900-generic #202010112230 SMP Sun Oct 11 22:34:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* **Consumer Pact library**: 2.0.0-beta.6
* **Provider Pact library**: -
* **Golang Version**: `go version go1.17.1 linux/amd64`
* **Golang environment**: Provide output of `go env`

## Expected behaviour

go package installs without incident.

## Actual behaviour

```
$ go get github.com/pact-foundation/pact-go/v2/@2.0.0-beta.6
github.com/pact-foundation/pact-go/v2 imports
        github.com/pact-foundation/pact-go/v2/command imports
        github.com/pact-foundation/pact-go/v2/installer imports
        github.com/hashicorp/go-getter imports
        cloud.google.com/go/storage imports
        google.golang.org/api/option imports
        google.golang.org/api/internal imports
        google.golang.org/grpc/naming: cannot find module providing package google.golang.org/grpc/naming
```

## Steps to reproduce

see above

## Relevent log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by mefellows** [comment]
Thanks, I'll have to take a look.

FWIW I know this build works, but it's with beta 5: https://github.com/pactflow/terraform-provider-pact/blob/master/Makefile#L59

**Comment by pcting** [comment]
There must be an issue with my environment. I have the same error with beta 5:
```
$ go get github.com/pact-foundation/pact-go/v2/@2.0.0-beta.5
github.com/pact-foundation/pact-go/v2 imports
        github.com/pact-foundation/pact-go/v2/command imports
        github.com/pact-foundation/pact-go/v2/installer imports
        github.com/hashicorp/go-getter imports
        cloud.google.com/go/storage imports
        google.golang.org/api/option imports
        google.golang.org/api/internal imports
        google.golang.org/grpc/naming: cannot find module providing package google.golang.org/grpc/naming
```

**Comment by pcting** [comment]
strange, this is what i get when i try to pull down that grpc package directly:
```
$ go get google.golang.org/grpc/naming
go get: module google.golang.org/grpc@upgrade found (v1.41.0), but does not contain package google.golang.org/grpc/naming
```

**Comment by pcting** [comment]
i'm closing this out. i was able to get pass this by passing `-u` in the argument:
```
$ go get github.com/pact-foundation/pact-go/v2/@2.0.0-beta.6
...
go get: upgraded github.com/pact-foundation/pact-go/v2 v2.0.0-20210621102432-26b32fd1552a => v2.0.0-beta.2.0.20210809072433-a3634c9437d7
```

**Comment by mefellows** [comment]
Thanks for the follow up!
