### ISSUE TITLE
Is there a way to pass PACT_DISABLE_SSL_VERIFICATION to Ruby-standalone from VerifyProvider?

### ISSUE THREAD

**Issue by HebosHebbe** [pact-foundation/pact-go#183]
## Software versions

* **OS**: Ubuntu latest
* **Consumer Pact library**: Pact go v1.6.4
* **Pact CLI**: Ruby-standalone 1.88.75
* **Golang Version**: 1.16

## Question

Is there a way to pass environment variable PACT_DISABLE_SSL_VERIFICATION=true to pact-ruby-standalone when running pact.VerifyProvider?

## Relevent log files
--- 🔨Running Provider Pact tests
go test -tags=contract -v -count=1 -run "TestPactProvider"
=== RUN   TestPactProvider
2021/10/05 09:34:36 [DEBUG] pact setup logging
2021/10/05 09:34:36 [DEBUG] pact setup
2021/10/05 09:34:36 [DEBUG] checking CLI compatibility
2021/10/05 09:34:36 [INFO] checking pact-mock-service within range >= 3.5.0, < 4.0.0
2021/10/05 09:34:36 [DEBUG] running binary pact-mock-service
2021/10/05 09:34:37 [DEBUG] checking version for binary pact-mock-service version 3.9.0
2021/10/05 09:34:37 [DEBUG] checking if version 3.9.0 within semver range >= 3.5.0, < 4.0.0
2021/10/05 09:34:37 [DEBUG] 3.9.0 satisfies constraints 3.9.0 >= 3.5.0, < 4.0.0
2021/10/05 09:34:37 [INFO] checking pact-provider-verifier within range >= 1.31.0, < 2.0.0
2021/10/05 09:34:37 [DEBUG] running binary pact-provider-verifier
2021/10/05 09:34:37 [DEBUG] checking version for binary pact-provider-verifier version 1.36.0
2021/10/05 09:34:37 [DEBUG] checking if version 1.36.0 within semver range >= 1.31.0, < 2.0.0
2021/10/05 09:34:37 [DEBUG] 1.36.0 satisfies constraints 1.36.0 >= 1.31.0, < 2.0.0
2021/10/05 09:34:37 [INFO] checking pact-broker within range >= 1.22.3
2021/10/05 09:34:37 [DEBUG] running binary pact-broker
2021/10/05 09:34:37 [DEBUG] checking version for binary pact-broker version 1.54.0
2021/10/05 09:34:37 [DEBUG] checking if version 1.54.0 within semver range >= 1.22.3
2021/10/05 09:34:37 [DEBUG] 1.54.0 satisfies constraints 1.54.0 >= 1.22.3
2021/10/05 09:34:37 [DEBUG] setting up a service manager
2021/10/05 09:34:37 [DEBUG] setting up a service manager
2021/10/05 09:34:37 [DEBUG] setting up a service manager
2021/10/05 09:34:37 [DEBUG] setting up a service manager
2021/10/05 09:34:37 [DEBUG] starting service removal monitor
2021/10/05 09:34:37 [DEBUG] starting service creation monitor
2021/10/05 09:34:37 [DEBUG] starting service removal monitor
2021/10/05 09:34:37 [DEBUG] starting service creation monitor
2021/10/05 09:34:37 [DEBUG] starting service creation monitor
2021/10/05 09:34:37 [DEBUG] starting service removal monitor
2021/10/05 09:34:37 [DEBUG] starting service creation monitor
2021/10/05 09:34:37 [DEBUG] starting service removal monitor
2021/10/05 09:34:37 [DEBUG] starting new proxy with opts {http 127.0.0.1:35697  0 [0xa713a0] /__setup <nil>}
2021/10/05 09:34:37 [DEBUG] starting reverse proxy on port 41703
2021/10/05 09:34:37 [DEBUG] waiting for port 41703 to become available on localhost after 10s
2021/10/05 09:34:37 [DEBUG] pact provider verification
2021/10/05 09:34:37 [DEBUG] client: verifying a provider
2021/10/05 09:34:37 [DEBUG] waiting for port 41703 to become available on localhost after 10s
2021/10/05 09:34:37 [DEBUG] starting verification service with args: [--format json --provider-base-url http://localhost:41703 --provider-states-setup-url http://localhost:41703/__setup --broker-username ***** --broker-password ****** --pact-broker-base-url https://****** --provider_app_version 0.0.1 --provider ***** --provider-version-tag  --provider-version-tag ]
    pact.go:418: error verifying the provider: see returned error for detail
    contract_test.go:34: error verifying provider: exit status 1

        STDERR:
        Error making request - OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=error: certificate verify failed , attempt 1 of 3
        Error making request - OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=error: certificate verify failed , attempt 2 of 3
        Error making request - OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=error: certificate verify failed , attempt 3 of 3

**Comment by mefellows** [comment]
It _should_ be passing it through as per https://github.com/pact-foundation/pact-go/blob/efb00ddb112c25a244949aa33750950b15b80a56/client/verification_service.go#L30.

I can't see in your log output above, have you set the environment variable (e.g. `export PACT_DISABLE_SSL_VERIFICATION=true` )?

I believe this should work though:
```sh
PACT_DISABLE_SSL_VERIFICATION=true go test -tags=contract -v -count=1 -run "TestPactProvider"
```

If you're able to tinker with the package locally to verify this isn't working and a solution to correctly pass it through, I'll happily update and push out a patch ASAP.

**Comment by HebosHebbe** [comment]
Typo from my side. Sorry about that. Thx for help!

I can confirm that above works.

**Comment by mefellows** [comment]
Great, thanks for clarifying!
