### ISSUE TITLE
v2: unable to determine current version of package libpact_ffi error on install

### ISSUE THREAD

**Issue by dabfleming** [pact-foundation/pact-go#191]
https://github.com/pact-foundation/pact-go/blob/965f5352245dd97adda9de8581c9469132e322a5/installer/installer.go#L125

`LibRegistry` is never populated:
```
log.Printf("[DEBUG] LibRegistry: %#v\n", LibRegistry)
// Prints: [DEBUG] LibRegistry: map[string]installer.Versioner{}
```
Results in always getting this error.

**Comment by dabfleming** [comment]
I had to delete /usr/local/lib/libpact_ffi.dylib manually and rerun `pact-go -l DEBUG install` to pick up the v0.1.0 change.

**Comment by mefellows** [comment]
This should be fixed now, as we store in a pact config directory the current known version, and we also print out what's being installed when it is.
