### ISSUE TITLE
Updated dependencies to fix CVEs

### ISSUE THREAD

**Issue by stefanello8** [pact-foundation/pact-go#196]
Version 1.6.7 has two CVEs related to the dependencies `github.com/gin-gonic/gin v1.7.2` ([vulnerability](https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMGINGONICGIN-1041736)) and `gopkg.in/yaml.v2 v2.2.2`  ([vulnerability](https://osv.dev/vulnerability/GO-2021-0061)) that could be fixed by bumping the dependencies to the latest version.

**Comment by mefellows** [comment]
Thanks, I'm surprised dependabot hasn't picked this up.

gin-gonic shouldn't actually be a dependency, we only use it in examples so I'll have those removed.

**Comment by YOU54F** [comment]
Ta, Yaml v2 now on version 2.4.0

https://github.com/pact-foundation/pact-go/blob/250ab07f38b166a6073e9d392e106357f1fc052c/go.mod#L16
