### ISSUE TITLE
Is there a plan to support GRPC?

### ISSUE THREAD

**Issue by nkguoym** [pact-foundation/pact-go#202]
Hi, Many services use grpc to communicate, is there any plan or idea on how to support GRPC contract test?

**Comment by mefellows** [comment]
Yes, via the [plugins](https://github.com/pact-foundation/pact-plugins) architecture and the v4 specification.

The current 2.x.x branch (next major) doesn't support plugins yet, but over the coming months we'll be adding support.

a gRPC plugin doesn't yet exist, but there is a protobufs one you could potentially use.

I'd suggest jumping into slack.pact.io and we can chat further there.

**Comment by nkguoym** [comment]
Thanks for your reply. will join slack and get more information

**Comment by nkguoym** [comment]
Thank you, will have a try.
