### ISSUE TITLE
Panic when running pact

### ISSUE THREAD

**Issue by azzamallow** [pact-foundation/pact-go#24]
Hey there,

I've recently started getting the following error when my pact tests. I can confirm this has been recently introduced, replacing my older version of the package (about 3 weeks old) with the most recent introduces the problem.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x139994f]

goroutine 35 [running]:
testing.tRunner.func1(0xc4201f4680)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x1408ea0, 0x169f6f0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/pact-foundation/pact-go/dsl.(*PactClient).VerifyProvider(0x0, 0xc42000c14b, 0x15, 0xc4201a5030, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	<hidden>/go/src/github.com/pact-foundation/pact-go/dsl/client.go:118 +0xef
github.com/pact-foundation/pact-go/dsl.(*Pact).VerifyProvider(0xc42024c000, 0xc42000c14b, 0x15, 0xc4201a5030, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	<hidden>/go/src/github.com/pact-foundation/pact-go/dsl/pact.go:219 +0xc2
<hidden>/deploy_test.TestPact(0xc4201f4680)
	<hidden>/pact_verify_test.go:37 +0x442
testing.tRunner(0xc4201f4680, 0x149f800)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca
```

**Comment by mefellows** [comment]
Thanks @azzamallow, based on the above trace and the most recent [change](https://github.com/pact-foundation/pact-go/commit/33a04342d19f0c5ee589b8fc8ff10ba97087700f#diff-e4be6756dd4720dd7cfb86d0e2a801edR118) that was made I'm assuming this breaks the Provider Verification process?

A colleague of mine did some digging and has traced it back to the above change. Specifically, it would make sense that line 117,118 has caused this. That's a bad oversight as it's obviously needed for Verification. Tests didn't pick this up as the E2E suite actually re-uses the Pact struct. I'll adjust this to make it more realistic.

In the meanwhile, we'll get a patch sorted for this asap.

**Comment by mefellows** [comment]
Hi @azzamallow, we've pushed out a fix for this to [v0.0.4](https://github.com/pact-foundation/pact-go/releases/tag/v0.0.4) - can you try with this version and let us know how you go?

**Comment by azzamallow** [comment]
@mefellows Thanks for the prompt response!

We can verify the latest fix fixes the problem we were having yesterday. Happy to have this issue closed.

**Comment by mefellows** [comment]
No worries, and sorry again!
