### ISSUE TITLE
provider state missing from gRPC contract

### ISSUE THREAD

**Issue by jasonltaylor** [pact-foundation/pact-go#253]
## Software versions

* **OS**: Ubuntu Linux
* **Consumer Pact library**: Pact Go CLI v2.0.0-beta.17
* **Provider Pact library**: Pact Go CLI v2.0.0-beta.17
* **Golang Version**: go version go1.19.2 linux/amd64
* **Golang environment**: 
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dev/.cache/go-build"
GOENV="/home/dev/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dev/go/pkg/mod"
GONOPROXY="github.hpe.com"
GONOSUMDB="github.hpe.com"
GOOS="linux"
GOPATH="/home/dev/go"
GOPRIVATE="github.hpe.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/dev/ws/sc-authz/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4109696144=/tmp/go-build -gno-record-gcc-switches"

## Expected behaviour

Provider state captured in contract JSON.

## Actual behaviour

Contract appears to be missing provider state details (no "providerStates"). Provider state handlers not called.

## Steps to reproduce

		Given("state one").
		UsingPlugin(message.PluginConfig{
			Plugin:  "protobuf",
			Version: "0.2.0",
		}).

## Relevent log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by mefellows** [comment]
Thanks for the report. I have just pushed 2a0f7cc which I think fixes this. Could you please let me know? (I've tested with the gRPC example in the code base).

**Comment by jasonltaylor** [comment]
Verified - tx!
