### ISSUE TITLE
RequestFilter no longer called for HTTP

### ISSUE THREAD

**Issue by jasonltaylor** [pact-foundation/pact-go#254]
## Software versions

* **OS**: Ubuntu Linux
* **Consumer Pact library**: Pact Go CLI v2.0.0-beta.17
* **Provider Pact library**: Pact Go CLI v2.0.0-beta.17
* **Golang Version**: go version go1.19.2 linux/amd64
* **Golang environment**: 
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dev/.cache/go-build"
GOENV="/home/dev/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dev/go/pkg/mod"
GONOPROXY="github.hpe.com"
GONOSUMDB="github.hpe.com"
GOOS="linux"
GOPATH="/home/dev/go"
GOPRIVATE="github.hpe.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/dev/ws/sc-authz/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4109696144=/tmp/go-build -gno-record-gcc-switches"

## Expected behaviour

RequestFilter set in VerifyRequest called during provider state verification. This was working with beta 15.

Ideally, since gRPC is an HTTP based protocol it would be nice if we could still pass an HTTP filter to inject headers but realize that may not be possible with the plugin framework.

## Actual behaviour

Request filter code not being called causing tests to fail.

## Steps to reproduce

I pretty much copied this code to inject a bearer token which is no longer getting called in beta 17:
https://github.com/pact-foundation/pact-go/blob/063ec5c8260769205638c7b3dd07d0ac6ad8088d/examples/mux/provider/user_service_test.go#L75

One other bit that may be relevant - I standup up my service in a container (providerBaseUrl points to a different host/IP) so the go provider test is a separate process. Not sure if that is relevant or not. I did not try to reproduce this with a single test binary serving as the providerBaseUrl and request filter.

## Relevent log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by mefellows** [comment]
Thanks for raising, i'll look into this now.
