### ISSUE TITLE
Interaction generated with V4 spec has request with redundant fields contentType and encoded

### ISSUE THREAD

**Issue by VikaKarman** [pact-foundation/pact-go#273]
## Software versions

* **OS**: Mac OSX 12.2
* **Consumer Pact library**: Pact Go CLI v2.0.0-beta.17/ V4
* **Provider Pact library**: Pact Go CLI v2.0.0-beta.17/ V4
* **Golang Version**: `go1.19.2 darwin/amd64`
* **Golang environment**: 

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/viktoriia.vlasiuk/Library/Caches/go-build"
GOENV="/Users/viktoriia.vlasiuk/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/viktoriia.vlasiuk/go/pkg/mod"
GONOPROXY="github.com/takeoff-com/*"
GONOSUMDB="github.com/takeoff-com/*"
GOOS="darwin"
GOPATH="/Users/viktoriia.vlasiuk/go"
GOPRIVATE="github.com/takeoff-com/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/viktoriia.vlasiuk/Work/Takeoff/projects/pact-go/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1k/l0smk_ys50556n0vm3rf5g6w0000gn/T/go-build3726273228=/tmp/go-build -gno-record-gcc-switches -fno-common"

## Expected behaviour

Generated interaction should not contain 

## Actual behaviour

Interaction request contains the following fields:
          "contentType": "application/json",
          "encoded": false

## Steps to reproduce

It can be seen in the generated pact in your repository:

https://github.com/pact-foundation/pact-go/blob/2.x.x/examples/pacts/PactGoV4Consumer-V4Provider.json#L29-L30

**Comment by mefellows** [comment]
This is how it is represented in the pact file for v4 interactions: https://github.com/pact-foundation/pact-specification/tree/version-4#synchronoushttp

What error are you actually seeing?

**Comment by VikaKarman** [comment]
I do not see any error. My tests just started failing when I moved to V4 because of these 2 fields. And I don't understand why we need them if we have request header "Content-Type" where we specify the format of request body. Here is our thread regarding this issue: https://pact-foundation.slack.com/archives/C9UTHTFFB/p1673601202990509 were  you seamed  to agree it was an issue

**Comment by mefellows** [comment]
As discussed, the confusion is that the current Pactflow UI does not know how to render V4 pacts which have a slightly different structure, and attempts to show what it knows.

Follow the item here for progress as to when that will be completed:
https://github.com/pactflow/roadmap/projects/1
