### ISSUE TITLE
gRPC example project is failing on GitHub Windows agent

### ISSUE THREAD

**Issue by rholshausen** [pact-foundation/pact-go#295]
## Software versions

* **OS**: Windows
* **Consumer Pact library**: v2.0.0-beta.21
* **Provider Pact library**: N/A
* **Golang Version**: 1.19.x
* **Golang environment**: CI

Example project https://github.com/pact-foundation/pact-plugins/tree/main/examples/gRPC/area_calculator/consumer-go was upgraded to the latest Pact-Go using the following commands:
```
go get github.com/pact-foundation/pact-go/v2
go mod vendor
```
See commit https://github.com/pact-foundation/pact-plugins/commit/5f293ae787a89522cd2f4d56b08c374999c97c71

The CI build is now failing on Windows (https://github.com/pact-foundation/pact-plugins/actions/runs/5206582349/jobs/9393298774) with the following error:
```
==== RUNNING consumer-go
# github.com/pact-foundation/pact-go/v2/internal/native
Error: vendor\github.com\pact-foundation\pact-go\v2\internal\native\message_server.go:505:97: cannot use _Ctype_ulong(i) (value of type _Ctype_ulong) as type _Ctype_ulonglong in variable declaration
Error: vendor\github.com\pact-foundation\pact-go\v2\internal\native\message_server.go:509:95: cannot use _Ctype_ulong(i) (value of type _Ctype_ulong) as type _Ctype_ulonglong in variable declaration
Error: Process completed with exit code 2.
```

**Comment by mefellows** [comment]
Hmm, interesting, thanks. I test on Windows here too and the gRPC tests are passing. I wonder if it's a C lib dependency or something going on, or version of Go.

**Comment by mefellows** [comment]
Yeah, I think it's the use of `size_t` here which is going to vary across OS/Architecturces
```
// Definition..
const unsigned char *pactffi_sync_message_get_response_contents_bin(const struct SynchronousMessage *message, size_t index);
size_t pactffi_sync_message_get_response_contents_length(const struct SynchronousMessage *message, size_t index);
```

But the implementation uses an unsigned long, which is a different type (but obviously matches the types on current targets).
```
len := C.pactffi_sync_message_get_response_contents_length(message, C.ulong(i))
if len == 0 {
	return nil, errors.New("retrieved an empty message")
}
data := C.pactffi_sync_message_get_response_contents_bin(message, C.ulong(i))
if data == nil {
	return nil, errors.New("retrieved an empty pointer to the message contents")
}
...
```

**Comment by mefellows** [comment]
@rholshausen released v2.0.0-beta.22 - mind seeing if the latest fixes it?

I think they're the only two locations in the code that have `size_t` in the signature that are explicitly typed in code - hence the compilation errors.

**Comment by rholshausen** [comment]
Lots of example projects are failing across different OSs for different reasons on GitHub. Something must have been changed on the agents.

**Comment by mefellows** [comment]
🤦 

Maybe you've been opted into an experiment :P

**Comment by rholshausen** [comment]
It is now failing with
```
==== RUNNING consumer-go
# area_calculator/consumer.test
C:\hostedtoolcache\windows\go\1.19.9\x64\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\RUNNER~1\AppData\Local\Temp\go-link-1851368132\000004.o: in function `_cgo_d1fc9e9a1507_Cfunc_pactffi_verifier_add_provider_transport':
C:\Users\runneradmin\AppData\Local\Temp\go-build3390115657\b091/cgo-gcc-prolog:94: undefined reference to `pactffi_verifier_add_provider_transport'
collect2.exe: error: ld returned 1 exit status
```
But only on Windows.

**Comment by rholshausen** [comment]
Ah, I think this is a build problem: https://github.com/pact-foundation/pact-plugins/blob/main/.github/workflows/examples.yml#L227

**Comment by rholshausen** [comment]
Green build!

**Comment by mefellows** [comment]
ah!

I noticed the `pact-go install` command is commented out. I thought I'd fixed it on Windows but perhaps I didn't.

I'll create a tracking issue to follow it up now.
