### ISSUE TITLE
Like() Matcher fails when a number is too large

### ISSUE THREAD

**Issue by antkazam** [pact-foundation/pact-go#3]
I guess because Golang numeric types and Ruby numeric types have different ranges.

`{
          "json_class": "Pact::SomethingLike",
          "contents": XXXXX
        }
`

When "contents" is a large int, it becomes interpreted by Ruby as a Float instead of a Fixnum. Therefore the provider validation will fail because it will have a decimal place added to it (1466191703.0 instead of 1466191703)

**Comment by mefellows** [comment]
Nice pickup @antkazam, hopefully we can make a fix in the upstream Pact gems to solve this one. Could you use the `Term()` matcher passing in a Regex in the meanwhile (just a guess, it might suffer the same fate)?

**Comment by mefellows** [comment]
The v2 specification has been implemented over at https://github.com/pact-foundation/pact-reference. This means we can drop the Ruby dependency soon in favour of a native library. It is on my todo list, I would estimate ~1 month or so before this has been completed. 

Will leave open for now.

**Comment by mefellows** [comment]
Update on this issue: we are still in the process of implementing the reference on the provider side (consumer-side is mostly completed in both this project and in the reference project). It's hard to approximate time, but please know we're working on it!

**Comment by bethesque** [comment]
I can't see why this is happening. If I do this, I get a Fixnum, not a Float.

```ruby
irb(main):006:0> JSON.parse('[146619170356]').first.class
=> Fixnum
```

**Comment by bethesque** [comment]
See build https://travis-ci.org/pact-foundation/pact-ruby-e2e-example/builds/245597866
for commit https://github.com/pact-foundation/pact-ruby-e2e-example/commit/1329d8c3b97321f4b6e094e639c2c69501dcecd2

**Comment by mefellows** [comment]
Just tested this with the following Pact:

```json
{
  "consumer": {
    "name": "billy"
  },
  "provider": {
    "name": "bobby"
  },
  "interactions": [
    {
      "description": "Some name for the test",
      "providerState": "Some state2",
      "request": {
        "method": "POST",
        "path": "/bazbat",
        "body": {
          "foo": 146619170312345678
        }
      },
      "response": {
        "status": 200,
        "headers": {},
        "body": [
          [
            {
              "colour": "red",
              "size": 10,
              "tag": [
                [
                  "jumper",
                  "shirt"
                ],
                [
                  "jumper",
                  "shirt"
                ]
              ]
            }
          ]
        ],
        "matchingRules": {
          "$.body": {
            "min": 1
          },
          "$.body[*].*": {
            "match": "type"
          },
          "$.body[*]": {
            "min": 1
          },
          "$.body[*][*].*": {
            "match": "type"
          },
          "$.body[*][*].colour": {
            "match": "regex",
            "regex": "red|green|blue"
          },
          "$.body[*][*].size": {
            "match": "type"
          },
          "$.body[*][*].tag": {
            "min": 2
          },
          "$.body[*][*].tag[*].*": {
            "match": "type"
          },
          "$.body[*][*].tag[*][0]": {
            "match": "type"
          },
          "$.body[*][*].tag[*][1]": {
            "match": "type"
          }
        }
      }
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "2.0.0"
    }
  }
}
``` 

and the body received by Go provider looks like this.

```json
{"foo":146619170312345678}
```

Tested on current master e8cc26504ad2167c29665f0d94adadd083e2444e

Please provide a repro and feel free to re-open.
