### ISSUE TITLE
Protobuf cannot find enum with multiple proto files

### ISSUE THREAD

**Issue by jasonltaylor** [pact-foundation/pact-go#334]
## Software versions

* **OS**: Debian Linux
* **Consumer Pact library**: Pact go v2.0.1 (main branch HEAD)
* **Provider Pact library**: Pact Go CLI v2.0.0-beta.22, protobuf 0.3.4
* **Golang Version**: go version go1.20.3 linux/amd64
* **Golang environment**: Provide output of `go env`

## Expected behaviour

Consumer tests executes successfully.

## Actual behaviour

`2023-09-06T15:39:03.780653Z ERROR ThreadId(01) pact_ffi::plugins: Failed to call out to plugin - Request to configure interaction failed: Failed to process protobuf: Protobuf enum value .routeguide.v2.ResultCode has no value RESULT_CODE_OK`

## Steps to reproduce

Pushed a PR with the gRPC consumer example updated with a second proto file to demonstrate the issue.
https://github.com/pact-foundation/pact-go/pull/333

## Relevent log files

See attached file.
[test_fail.txt](https://github.com/pact-foundation/pact-go/files/12539810/test_fail.txt)

**Comment by mefellows** [comment]
Issue looks to be related to https://github.com/pactflow/pact-protobuf-plugin/pull/31.
See #333 for repro.

**Comment by jasonltaylor** [comment]
verified fixed with protobuf plugin 0.3.6

**Comment by mefellows** [comment]
Closed in #333 .
