### ISSUE TITLE
How to specify Pact CLI path in Go package manager

### ISSUE THREAD

**Issue by galaxy79** [pact-foundation/pact-go#337]
Our CI server dont have the PACT CLI installed and the teams using the pact-go is seeing error when running the contract tests in CI server. Is there a way for teams to have the cli in their repo and mention it go package manager, so that go pact sdk can use that cli for the contract tests ? I do see similar capability exist on the node and pact node version (9) allows us to test using it

**Comment by mefellows** [comment]
It currently doesn't but I'd support a PR that allowed an environment variable to specify the path.

Come to think of it, you could also just set `PATH` in your build to include the folder in your project (simpler).

**Comment by mefellows** [comment]
No worries, thanks!

**Comment by mefellows** [comment]
Yep, I'm happy to accept a PR to that branch.

**Comment by YOU54F** [comment]
completed and released https://github.com/pact-foundation/pact-go/pull/357#issuecomment-2151385739

thanks for the contribution team!
