### ISSUE TITLE
Integration test error is ignored in dsl.pact.verify()

### ISSUE THREAD

**Issue by liamawhite** [pact-foundation/pact-go#37]
From looking at the code it seems that any error the passed in function returns is ignored.

https://github.com/pact-foundation/pact-go/blob/master/dsl/pact.go#L182

Seems to match what I'm seeing in my tests as well; my client is erroring but my tests all pass.

```
if err := pact.Verify(c.testFunc); err != nil {
	t.Fatalf(err.Error())
}
```

**Comment by mefellows** [comment]
Yep, this is a good point.

The current focus as you can see is the fail wrt Pact - but a failure in the integration test itself is also a failure!

**Comment by mefellows** [comment]
Wercker is being a jerk and there is some issue with artefacts persisting between build steps (or I've misunderstood how it works). I've pushed a fix in any case, you're welcome to pull it down and compile locally to see if this sorts it out.

**Comment by liamawhite** [comment]
Thanks, I'll give this a go.

**Comment by mefellows** [comment]
I've fixed the Wercker build now. When you get a moment, can you please check out `v0.0.8` on your code?

**Comment by liamawhite** [comment]
@mefellows just tested `v0.0.8` with the fix/37 branch, works as expected.

**Comment by mefellows** [comment]
Thanks @liamawhite, closing.

**Comment by liamawhite** [comment]
@mefellows Thanks for the quick fix. Any ideas when it will be merged into master?

**Comment by mefellows** [comment]
Wow, you were quick - merged :)
