### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by davidkuridza** [pact-foundation/pact-go#415]
Hi,

I can't find information on the release cycle, is it done sporadically or is there a defined one in place? Do you reckon it would be possible to create a new one soon?

Two dependencies listed below have vulnerabilities causing our pipeline to fail. The fix was merged with #392 

```
+-------------------------------------+------+-----------+--------------------------------+-----------+
| OSV URL                             | CVSS | ECOSYSTEM | PACKAGE                        | VERSION   |
+-------------------------------------+------+-----------+--------------------------------+-----------+
| https://osv.dev/GO-2022-0646        |      | Go        | github.com/aws/aws-sdk-go      | v1.44.298 |
| https://osv.dev/GHSA-q64h-39hv-4cf7 | 9.8  | Go        | github.com/hashicorp/go-getter | v1.7.3    |
+-------------------------------------+------+-----------+--------------------------------+-----------+
```

Thank you.

**Comment by mefellows** [comment]
It's usually when something useful is ready to release. I'll do a release now.

**Comment by mefellows** [comment]
done - `v2.0.5` is out.

**Comment by mefellows** [comment]
(Actually, I'll need to follow the actions after I get off the train, but it _might_ be going out just now...)

**Comment by davidkuridza** [comment]
Thank you very much for your prompt response, was not expecting it to happen so fast. I owe you one :)

**Comment by mefellows** [comment]
Haha no worries, enjoy the builds ;)
