### ISSUE TITLE
Ensure PACT_DESCRIPTION and PACT_PROVIDER_STATE env vars can be passed down to pact verify to allow selected interactions to be run

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-go#44]
_This probably belongs in a child repo, I'm just not sure which one, so raising here!_

I've removed the ruby specific output from the pact verify command (yay!)

What I would like to add is words to the effect of "to run just one interaction, please rerun the pact verify command with PACT_DESCRIPTION="..." and PACT_PROVIDER_STATE="..." environment variables set.

Can you please update to the ruby standalone version 1.4.0 and verify that the above environment variables are passed through? You should see the text `Filtering interactions by...`

See https://github.com/pact-foundation/pact-js/issues/84

**Comment by mefellows** [comment]
@bethesque from the provider side, how would we determine which provider description/state to tell the user? It's quite a blunt instrument at the moment as we get back only unstructured data from a single call to 'verify'.

I see a few options here:

1. Have the verifier (and mock service?) send back structured data that the client libraries can use more intelligently (this might be required for other scenarios, such as message/other engine support)
1. Have the verifier output a generic message as per your suggestion that doesn't
1. Have a clear message in the unstructured data that can be filtered and used to make this decision
1. Something else I can't imagine at this moment in time

**Comment by mefellows** [comment]
FWIW it's worth, it works for Pact Go:

```
PACT_DESCRIPTION="yeah" PACT_PROVIDER_STATE="blah" make pact
...
Reading pact at /Users/mfellows/go/src/github.com/pact-foundation/pact-go/examples/e2e/../pacts/billy-bobby.json
Filtering interactions by: {:description=>/yeah/, :provider_state=>/blah/}
No examples found.

0 interactions, 0 failures
```

**Comment by bethesque** [comment]
For each failure in the pact, the ruby code outputs the command to run that individual interaction (you probably just gloss over that as it's not relevant for js/go). 

```
Failed interactions:

bundle exec rake pact:verify:at[./spec/support/test_app_fail.json] PACT_DESCRIPTION="a test request" PACT_PROVIDER_STATE="the weather is cloudy" # A test request given the weather is cloudy
bundle exec rake pact:verify:at[./spec/support/test_app_fail.json] PACT_DESCRIPTION="another test request" PACT_PROVIDER_STATE="" # Another test request
bundle exec rake pact:verify:at[./spec/support/test_app_fail.json] PACT_DESCRIPTION="another test request" PACT_PROVIDER_STATE="a missing provider state" # Another test request given a missing provider state
```

If the calling code can also set an environment variable called `PACT_INTERACTION_RERUN_COMMAND` then I can use that to create language specific re-run commands. Otherwise, I can just print the description/state env vars for each interaction, with the text "Please re-run the verify command with the relevant env vars set to run an individual interaction"

**Comment by bethesque** [comment]
The value of `PACT_INTERACTION_RERUN_COMMAND` for ruby is 

```
bundle exec rake pact:verify:at[<PACT_URI>] PACT_DESCRIPTION=\"<PACT_DESCRIPTION>\" PACT_PROVIDER_STATE=\"<PACT_PROVIDER_STATE>\"
```

I substitute in the relevant description, state and URL.

**Comment by mefellows** [comment]
Yep, but it doesn't do that anymore right?

`PACT_INTERACTION_RERUN_COMMAND` seems like a good suggestion. Is that already available?

**Comment by bethesque** [comment]
I've already done it.

**Comment by mefellows** [comment]
I think that was a race condition - I can do that :)

**Comment by mefellows** [comment]
I've updated the code base to set `PACT_INTERACTION_RERUN_COMMAND` when running the verification process. Let us know when it's in the upstream package. I'm running it locally against 1.4.2 and it's still wanting to do Ruby stuff.

**Comment by bethesque** [comment]
Bother, I thought I had already. Will go and check my releases.

**Comment by bethesque** [comment]
It's working for me with 1.4.2. If I run

```
PACT_INTERACTION_RERUN_COMMAND="foo" ./pact-provider-verifier -a "1.0.100" --provider-base-url http://localhost:4567 --pact-urls fail.json --provider_states_setup_url http://localhost:4567/provider-state -v
```

I get:
```
3 interactions, 2 failures

Failed interactions:

foo # Greeting fail
foo # Provider state success
```

**Comment by mefellows** [comment]
I worked out why - we use the `--json` flag and it doesn't seem to come through in there (and for good reason).

I'll update docs and have the code pass it through anyway for future safe-keepings.
