### ISSUE TITLE
How to specify provider name in verify request

### ISSUE THREAD

**Issue by zbintliff** [pact-foundation/pact-go#53]
Hey quick question I can't grok from the docs.  We have 4 clients each pulling from 4 providers.  Lets call the providers A,B,C and D.  I push all the pacts to my broker. When looking at `VerifyRequest` I can't really figure out how to specify I want all the the latests pacts for tag `foo` where the provider is `B`.

**Comment by mefellows** [comment]
Can I just clarify the use case here. If `Client A` is one of those clients, does it rely on _all four_ providers?

**Comment by zbintliff** [comment]
Sorry A-D are providers. We have one client that will generate 1 pact per pair for a total of 4 pacts.

Lets call our client "client". It seems the only way of doing it (that I can tell is to use [option 1 listed here](https://github.com/pact-foundation/pact-go#provider-verification) and provide the specific url. That is:

```
response = pact.VerifyProvider(types.VerifyRequest{
	ProviderBaseURL:        "http://myproviderhost",
	PactURLs:               []string{"http://broker/pacts/provider/B/consumer/client/latest/TAG_I_WANT_TO_TEST"},		
})
```

**Comment by zbintliff** [comment]
It would be nice if we could use option 3 from the above link and do this:
```
response = pact.VerifyProvider(types.VerifyRequest{
    ProviderBaseURL:        "http://myproviderhost",
    BrokerURL:              "http://brokerHost",
    ProviderName: "B",
    Tags:                   []string{"latest", "sit4"},    
})
```

Becuase without limiting to provider "B" it will pick up the other providers pacts that are also tagged "latest". Does this make sense?

**Comment by zbintliff** [comment]
Nevermind, I'm an idiot. `VerifyProvider` is a method of `Pact` which already has the info. ITs not very clear in the docs but thats my bad.

**Comment by mefellows** [comment]
I was just doing a confirmation of this on the test.pact.dius.com.au broker, but glad you worked it out.

If this wasn't clear to you, it probably isn't clear to others either. How should we fix the docs to make it clearer, given that you were just surprised by it I'd like to tap into your brain!

**Comment by zbintliff** [comment]
The code block from [provider](https://github.com/pact-foundation/pact-go#provider) uses the `pact` variable which I thought was the package.  In the consumer section you walk through creating the `pact` variable via `dsl.pact{}` but it was never mentioned in the the provider section to recreate the `pact`.

If that makes sense. I was just diving into the provider side, writing docs and standards for our team to use when deploying versions and tags. If i was writing the code I probably would have figured it out right away.

**Comment by mefellows** [comment]
OK yeah I gotcha. I'm looking forward to the day that I can make those code snippets testable!
