### ISSUE TITLE
Pact::UnexpectedIndex on provider verification

### ISSUE THREAD

**Issue by zbintliff** [pact-foundation/pact-go#54]
## Software versions

* **OS**: e.g. Mac OSX 10.11.5
* **Consumer Pact library**:  Pact go v0.0.10
* **Provider Pact library**: Ruby standalone 1.4.2 i believe (whatever pact-go installs)
* **Golang Version**: 1.9.1
* **Golang environment**: 
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/bintliff/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/t2/pn8d2qc91_b8l60s1jq5lf0w0000gn/T/go-build850475455=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```
## Expected behaviour

Allow more than one item of the array when `EachLike(x, 1)` is passed.  The array provider returns contains two items.

## Actual behaviour

Fails on verification with `Pact::UnexpectedIndex` error

## Steps to reproduce

https://github.com/zbintliff/pact-ruby-standalone-e2e-example/tree/issue/unexpected-index

## Relevent log files

Recreatable above

**Comment by zbintliff** [comment]
Hey @mefellows been working through this for way longer than I like to admit but i figured out _why_.  Its because we have a `EachLike` within a `Like`. I assumed it  was allowed because in the example you have an `EachLIke` within an `EachLike` but i guess its is not. If you remove the type matcher on the `body` it will work.

**Comment by zbintliff** [comment]
Will leave to you if we leave this open or not as I'm not sure what is, or isn't expected behaviour.

**Comment by mefellows** [comment]
I think this is a common confusion, I should fix the examples as the nested `*Like` is not necessary, apologies for this (I actually didn't understand this when first creating this library). Perhaps we should not allow this sort of nesting in the DSL itself, or at the very least log a `WARN`?

**Comment by zbintliff** [comment]
Yeah, it got me good.  If we could warn that would be nice.

I can see an argument for both. If I say `Like({"a": [], "b":"xx"})`. Should it fail if `a` doesn't match  length? By definition it should only match type.  I could be speaking nonsense cause I've been staring at this for a while though.

**Comment by bethesque** [comment]
I've raised an enhancement issue in pact-support.

@zbintliff if you're game to wade in to the code, you could have a go at a PR. It looks like you've already gotten your hands dirty! It will either be in the writing of the rules here: https://github.com/pact-foundation/pact-support/tree/master/lib/pact/matching_rules/extract.rb or the merging (turning the rules back into Ruby objects) here: https://github.com/pact-foundation/pact-support/tree/master/lib/pact/matching_rules/merge.rb

**Comment by bethesque** [comment]
This turned out to be a fiddly one. Sorry it's taken so long. Please upgrade to v1.54.1 of the standalone @mefellows

**Comment by mefellows** [comment]
Thanks Beth. I've pushed out an update just now.

As an FYI, Pact Go doesn't need direct updates these days (the CLI tools is a separate installation step for users, so they can update independent of Pact Go) - this was to make Pact more idiomatic in the Go ecosystem according to the will of the people. I have updated the minimum version constraints however to ensure people upgrade.
