### ISSUE TITLE
Fail to run example.  [ERROR] service fork/exec /Users/ypwu1/dev/github/pact-go/pact-mock-service/bin/pact-mock-service: no such file or directory

### ISSUE THREAD

**Issue by ypwu1** [pact-foundation/pact-go#6]
I have  go1.6 installed  on mac,  I followed the README step by step. When running "go run consumer.go" , it throws an error immediately: 
```
Error on Verify: Post http://localhost:0/interactions: dial tcp [::1]:0: connect: can't assign requested address exit status 1
```

 On the pact-go console also throws error as well:
```
 [ERROR] service fork/exec /Users/ypwu1/dev/github/pact-go/pact-mock-service/bin/pact-mock-service: no such file or directory
```
here is my go env:
GOARCH="amd64"
GOBIN="/Users/ypwu1/.gopm/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ypwu1/.gopm"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6.2/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**Comment by mefellows** [comment]
Hi @ypwu1, it looks like the Daemon is unable to start the (external Ruby) mock service. How are you running the daemon? Note that you must download a [release](https://github.com/pact-foundation/pact-go/releases) package and run the daemon from that binary.

I have also updated that example (the space in `"My Consumer"` and `"My Provider"` is invalid) and the main README.

**Comment by ypwu1** [comment]
Hi @mefellows, thanks your help. I just pull down the latest and run.  It seems working fine and  generates the pact file. Only the log tells it's error to generate pact file.  
```
2016/07/10 23:40:04 [INFO] daemon - starting daemon on port 6666
2016/07/10 23:40:04 method Shutdown has wrong number of ins: 1
2016/07/10 23:40:04 method StartDaemon has wrong number of ins: 2
2016/07/10 23:43:03 [INFO] service: No entry for terminal type "xterm-256color";
2016/07/10 23:43:03 [INFO] service: using dumb terminal settings.
2016/07/10 23:43:03 [INFO] service: ERROR: "pact-mock-service.rb service" was called with arguments ["Consumer", "Provider"]
2016/07/10 23:43:03 [INFO] service: Usage: "pact-mock-service.rb service"
2016/07/10 23:46:39 [INFO] service: No entry for terminal type "xterm-256color";
2016/07/10 23:46:39 [INFO] service: using dumb terminal settings.
2016/07/10 23:46:40 [INFO] service: [2016-07-10 23:46:40] INFO  WEBrick 1.3.1
2016/07/10 23:46:40 [INFO] service: [2016-07-10 23:46:40] INFO  ruby 2.1.5 (2014-11-13) [x86_64-darwin13.0]
2016/07/10 23:46:40 [INFO] service: [2016-07-10 23:46:40] INFO  WEBrick::HTTPServer#start: pid=8808 port=62362
2016/07/10 23:46:40 [INFO] service: [2016-07-10 23:46:40] INFO  going to shutdown ...
2016/07/10 23:46:40 [INFO] service: [2016-07-10 23:46:40] INFO  WEBrick::HTTPServer#start done.
2016/07/10 23:46:40 [ERROR]
2016/07/10 23:46:40 [ERROR] Writing pact for MyProvider to /Users/ypwu1/dev/github/pact-go/examples/pacts/myconsumer-myprovider.json
```

**Comment by mefellows** [comment]
Excellent! Unfortunately that `[ERROR]` is part of the mock service
(written to stderr).
