### ISSUE TITLE
cookie support

### ISSUE THREAD

**Issue by mohanraj-r** [pact-foundation/pact-go#69]
Is there existing or planned support for specifying cookies in interactions ?
Having some issues writing pact tests around a service which relies on cookie for auth - can you please help me.

## Software versions
* **OS**: Mac OSX 10.13.2 
* **Consumer Pact library**: 
```
$ pact-go version
Pact Go CLI v0.0.11
```
* **Provider Pact library**: [v0.0.12](https://github.com/pact-foundation/pact-go/releases/download/v0.0.12/pact-go_darwin_amd64.tar.gz)
* **Golang Version**: `go1.10 darwin/amd64`
* **Golang environment**: Provide output of `go env`
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mohanrajr/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mohanrajr/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/d0/742yxrrx0glg93s4z_rwyzkxm0whbv/T/go-build258382301=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

## Expected behaviour
* Ability to specify cookies in interactions

## Actual behaviour
* No existing support for cookies in interactions

## Steps to reproduce
* I am writing pact tests for a service which does basic auth to login and then subsequent reqs are authenticated with a cookie
   - e.g. first req to login using basic auth
   - subsequent reqs authenticated by sending cookie
* Since there is no current method to specify a cookie, I tried setting the auth header for subsequent reqs
   - but this doesn't work because the test fails because it doesn't see the same auth header in the actual request (see log below)
   - not specifying the auth header makes the `VerifyProvider()` test to fail - since trying to /logout without a cookie or auth header results in a 401 instead of the expected 200 status

## Relevent log files

```

E, [2018-03-13T19:33:34.040449 #50904] ERROR -- : No matching interaction found for POST /logout
E, [2018-03-13T19:33:34.040486 #50904] ERROR -- : Interaction diffs for that route:
E, [2018-03-13T19:33:34.040957 #50904] ERROR -- : Diff with interaction: "A request to logout"
Diff
--------------------------------------
Key: - is expected 
     + is actual 
Matching keys and values are not shown

 {
   "headers": {
-    "Authorization": "Basic XXX="
   }
 }

Description of differences
--------------------------------------
* Could not find key "Authorization" (keys present are: Content-Type, Host, User-Agent, Accept-Encoding, Version) at $.headers

I, [2018-03-13T19:33:34.044004 #50904]  INFO -- : Writing pact for WAPIIntegration to

```

**Comment by mohanraj-r** [comment]
Tried sending cookie via interaction header using `set-cookie`
```go
pact.
    AddInteraction().
    ...
    WillRespondWith(dsl.Response{
				Status: http.StatusOK,
				Headers: map[string]string{
					"set-cookie": dsl.Like(`auth="group=testing,ctime=1520989773,"; httponly; Path=/; secure`),
				},
			})
```

But I am not seeing the cookies in `pact.Verify()`
```go
err = pact.Verify(func() error {
			resp, err := s.Login()
			t.Run("cookie check", func(t *testing.T) {
				// set cookies to be reused in subsequent requests
				cookies := resp.Cookies()
				require.Len(t, cookies, 1) // fails because there are no cookies
				authCookie = cookies[0]
			})
```

**Comment by abubics** [comment]
It sounds like you're trying to verify behaviour with Pact. That's not what it's for :)

From your description, it seems like maybe logging in would be one action to test, and subsequent actions would be separate individual tests.

If the cookies are part of the client state, then they would be implied by the `given` block.
e.g. "given a logged in user ...", then set the cookies for that state.

**Comment by mefellows** [comment]
OK there are a few things here:

2. it did work, it just didn't come back as a cookie as you expected (look at your headers, I bet it's there). I've tested by adding `"Cookie": `auth="group=testing,ctime=1520989773,"; httponly; Path=/; secure`,` to the response headers in consumer test in the examples
1. `set-cookie` is an action as per @abubics comment. It won't be interpreted by the mock server and then sent back as `cookie`. You probably want to use just `cookie`
1. Depending on how this authentication cookie is generated, it might be time-bound and therefore by the time the provider gets to verifying it, the authorisation information in the pact could be out of date. If this is the case, take a look at [this](https://github.com/pact-foundation/pact-go#api-with-authorization). Not saying it's necessarily the case, but something to note.

**Comment by mohanraj-r** [comment]
> It sounds like you're trying to verify behaviour with Pact. That's not what it's for :)
@abubics I know :) My use case is a bit weird in that I am using it to write tests for a lib that interacts with a 3rd party service (provider). Not sure if there is a better way to go about it.

Btw, how could I use `Given()` to set cookies ?

@mefellows Thanks for the followup
* Tried setting `"Cookie": .." in `Headers` - but couldn't get it to work. Not getting cookie back in response object. Not sure what I am doing wrong.
* Tried using `CustomProviderHeaders` and it works! thanks.

**Comment by abubics** [comment]
Maybe my suggestion isn't appropriate for your use case, so please don't take it as a definite solution ;)

My general approach is to think about how it should work on both sides of the Pact test.

This is the consumer-side interaction specification, right? If you're expecting a header to come back in the response from the provider, just specify the header in the response setup. As @mefellows mentioned, you should be able to find a working version in examples :) Is `CustomProviderHeaders` all you needed?

What would you do on the provider side to test this, though? You get `set-cookie` as a header in the request for the login? But what do you get in subsequent requests?

Anyway, if your problem is solved now, don't feel like you have to continue this thread :P
