### ISSUE TITLE
How can pact handle dynamic bits in URL and query params ?

### ISSUE THREAD

**Issue by mohanraj-r** [pact-foundation/pact-go#72]
I am trying to test a complex interaction :
1. Issue a Get req against a specific path with a specific query parm - returns a result with a dynamic ref id
2. Subsequent Post req against a path composed of the dynamic ref id obtained in step 1 to get a dynamic value
3. Subsequent Get req against a static path with a query param constructed with the value obtained in step 2

How can I do this with Pact? 
* Tried using [dsl.Like](https://github.com/pact-foundation/pact-go/#matching-consumer-tests) - but looks like its supported only for body ?

## Software versions
* **OS**: Mac OSX 10.13.2 
* **Consumer Pact library**: 
```
$ pact-go version
Pact Go CLI v0.0.11
```
* **Provider Pact library**: [v0.0.12](https://github.com/pact-foundation/pact-go/releases/download/v0.0.12/pact-go_darwin_amd64.tar.gz)
* **Golang Version**: `go1.10 darwin/amd64`
* **Golang environment**: Provide output of `go env`
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mohanrajr/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mohanrajr/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/d0/742yxrrx0glg93s4z_rwyzkxm0whbv/T/go-build258382301=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by mefellows** [comment]
Hi @mohanraj-r,

You are talking about _functional testing_, which is not something Pact supports. Each interaction must strictly be able to be validated in isolation from another. To achieve this, we use ["provider states"](https://github.com/pact-foundation/pact-go#provider-verification).

See https://docs.pact.io/best_practices/contract_tests_not_functional_tests.html for a discussion of these functional tests.

If I have misunderstood, and your request is more about being able to match the request path/headers/etc. using matchers, I've just come across a bug for that (related to a @gallamine query) and will release a fix in the next few days.

**Comment by mohanraj-r** [comment]
> we use "provider states".

Thanks @mefellows 
Can you give me an example of how to setup provider states in Go? 
Looked at [Provider States · Pact](https://docs.pact.io/documentation/ruby/provider_states.html) - but the examples are in Ruby - not clear how I can do the same in Go.

> more about being able to match the request path/headers/etc. using matchers
Yes, having the ability to use matchers in the req URL, query etc could be helpful for me in this case as well

**Comment by mefellows** [comment]
Have you looked at the [examples](https://github.com/pact-foundation/pact-go/blob/master/examples/)? The [mux](https://github.com/pact-foundation/pact-go/blob/master/examples/mux/provider/user_service_test.go#L86-L129) example shows how to achieve this with the in-built `http` package.

The [readme](https://github.com/pact-foundation/pact-go/#provider) also explains this in the provider section.

Hope that helps.
