### ISSUE TITLE
Installation check fails because of warning

### ISSUE THREAD

**Issue by gaelduplessix** [pact-foundation/pact-go#85]
## Software versions

* **OS**: Docker container based on `golang:1.9`
* **pact-go**: `v1.0.0-beta`

## Expected behaviour

Tests run properly.

## Actual behaviour

```
[INFO] checking pact-mock-service within range >= 2.6.4, < 3.0.0
[ERROR] CLI tools are out of date, please upgrade before continuing
```

## Investigation

- In [`checkCliCompatibility`](https://github.com/pact-foundation/pact-go/blob/master/dsl/pact.go#L331), the underlying error is not printed, so I had to manually run `pact-mock-service version` to troubleshoot. 
- By running the command manually, I got
```
/opt/pact/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /go/bin in PATH, mode 040777
2.7.1
```
I guess I could prevent the warning from appearing but still, the version checking code should probably ignore the warning lines. Maybe using a regexp to catch the line with the version or just read the last line.

## Workaround

For now, I used [`DisableToolValidityCheck: true`](https://github.com/pact-foundation/pact-go/blob/master/dsl/pact.go#L89) to disable version check altogether

**Comment by mefellows** [comment]
Thanks @gaelduplessix, I'll look into it. At least printing out the error would be useful!

**Comment by jaswanthm** [comment]
Thanks for the workaround @gaelollivier 🙏
