### ISSUE TITLE
Running `make testrace` fails with `race detected during execution of test`

### ISSUE THREAD

**Issue by rasmus-unity** [pact-foundation/pact-go#89]
We're running our unit tests with `-race` option, and when trying to introduce pact consumer tests, they fail with a race condition. Reproduced on latest master from https://github.com/pact-foundation/pact-go repo. We can probably find a way to run pact tests without race detection, but curious to know if this is an issue which should be fixed.

## Software versions

* **OS**: Mac OSX 10.13.5
* **Consumer Pact library**: From https://github.com/pact-foundation/pact-go/commit/6c1c6ad5447f5e96e2aa37f0cf069071faef8d10 (`master` branch)
* **Provider Pact library**: Same repo
* **Golang Version**: `go version go1.9.4 darwin/amd64`
* **Golang environment**: 
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/rasmuss"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/07/fstlw6z54j53s4lndk0f4vgw0000gp/T/go-build243676548=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

## Expected behaviour

Running pact tests with `-race` should pass

## Actual behaviour

Fails with
```
==================
WARNING: DATA RACE
Read at 0x00c420148480 by main goroutine:
  runtime.mapaccess1_fast64()
      /usr/local/opt/go/libexec/src/runtime/hashmap_fast.go:110 +0x0
  github.com/pact-foundation/pact-go/client.(*ServiceManager).Stop()
      /Users/rasmuss/src/github.com/pact-foundation/pact-go/client/service_manager.go:65 +0x16d
  github.com/pact-foundation/pact-go/client.(*MockService).Stop()
      <autogenerated>:1 +0x51
  (...)

Previous write at 0x00c420148480 by goroutine 8:
  runtime.mapassign_fast64()
      /usr/local/opt/go/libexec/src/runtime/hashmap_fast.go:598 +0x0
  github.com/pact-foundation/pact-go/client.(*ServiceManager).addServiceMonitor()
      /Users/rasmuss/src/github.com/pact-foundation/pact-go/client/service_manager.go:41 +0x165

Goroutine 8 (running) created at:
  github.com/pact-foundation/pact-go/client.(*ServiceManager).Setup()
      /Users/rasmuss/src/github.com/pact-foundation/pact-go/client/service_manager.go:30 +0x1be
  github.com/pact-foundation/pact-go/client.(*MockService).Setup()
      <autogenerated>:1 +0x43
  github.com/pact-foundation/pact-go/dsl.newClient()
      /Users/rasmuss/src/github.com/pact-foundation/pact-go/dsl/client.go:43 +0x42
  (...)
```

## Steps to reproduce

1. `git clone git@github.com:pact-foundation/pact-go.git`
1. `cd pact-go`
1. `make testrace`

EDIT: Alternatively

1. `git clone git@github.com:pact-foundation/pact-go.git`
1. `cd pact-go/examples/consumer/goconsumer`
1. `go test -race -run TestPactConsumerLoginHandler_UserExists .`

Result: `Found 2 data race(s)`

## Relevent log files

Hope above is sufficient

**Comment by mefellows** [comment]
The mock server it starts is stateful, as it needs to confirm the the expected interactions for each test are actually made, so running the pact tests in parallel is not possible, unless you create multiple instances of the pact struct on different ports.

See https://github.com/pact-foundation/pact-go/blob/master/README.md#splitting-tests-across-multiple-files for some insight into how you might be able to achieve it

**Comment by mefellows** [comment]
Sorry, didn't mean to hot close. Will look into it and add some documentation for others

**Comment by rasmus-unity** [comment]
Updated description above to include repro steps for issue when running single consumer pact test from `pact-go/examples/consumer/goconsumer`. Hope I understood correctly, that this should be possible?

**Comment by mefellows** [comment]
That's fantastic, thanks! It should be possible to run the test, so looks like a bug we can hunt down.

**Comment by mefellows** [comment]
Fix is now in master, but not in a tagged release. If you'd like to give this a go in your project @rasmus-unity that'd be great.

**Comment by rasmus-unity** [comment]
@mefellows, verified it works on our test suite also. thanks for the quick fix to this!

**Comment by mefellows** [comment]
Your welcome, thanks!
