### ISSUE TITLE
Getting metadata  in VerifyMessageConsumer handler

### ISSUE THREAD

**Issue by alexeits** [pact-foundation/pact-go#95]
## Software versions

* **OS**: e.g. macOS 10.13.6 (17G65)
* **Consumer Pact library**: e.g. pact-go v1.0.0-beta.2

**Is there an idiomatic way to get metadata values in VerifyMessageConsumer?**

## Expected behaviour

I have metadata set up as follows:
```go
WithMetadata(dsl.MapMatcher{
	"correlationId": dsl.Like("updaterCorrelationId"),
	"topic": dsl.Term("orgs/example/configuration", "orgs/[^/]+/configuration"),
})
```
It  would be nice to get metadata values in VerifyMessageConsumer like this:
```go
pact.VerifyMessageConsumer(t, message, func(m dsl.Message) error {
	handler.Invoke(&Context{
		CorrelationID: m.Metadata.Get("correlationId"),
		Topic:         m.Metadata.Get("topic"),
	}, *m.Content.(*Payload))
})
```

## Actual behaviour

Instead I have to do something that looks pretty dependent on the internals of the metadata matchers:
```go
pact.VerifyMessageConsumer(t, message, func(m dsl.Message) error {
	handler.Invoke(&Context{
		CorrelationID: m.Metadata["correlationId"].(dsl.Matcher)["contents"].(string),
		Topic:         m.Metadata["topic"].(dsl.Matcher)["data"].(map[string]interface{})["generate"].(string)),
	}, *m.Content.(*Payload))
})

```

**Comment by mefellows** [comment]
It's a nice idea, would you be willing to submit a PR? I could probably get to it over the next few weeks otherwise.

**Comment by alexeits** [comment]
Possibly, I haven't given much thought to potential implementations yet. I  might be able to look into it next week.
