### ISSUE TITLE
How to test a provider with a required incrementing version field?

### ISSUE THREAD

**Issue by fewstera** [pact-foundation/pact-go#99]
Hi,

This is something that may not be possible currently, I'm just wondering if you know of a nice way I could achieve it.

When consumers send updates to an object to the provider we require that they send the most current version number of the object that they know about. When the provider persists the update it increments the version number.

For example, say we have an object 1 that looks like:
```
{"id": "1", "version": 1, "body": "Hello, World!"}
```

If we were to send an update to that object we would send a request like:
```
PATCH /story/1
X-version: 1
{"body": "New body!"}
```

The object would then be persisted as:
```
{"id": "1", "version": 2, "body": "New body!"}
```

If the consumer's version number does not match the current version on the provider then the request is rejected with a 409 conflict.

Now I'd like to add CDC tests to the provider, but I can't find a way to dynamically set the X-version header for each individual request, so that it always matches the current version on the server (to avoid 409 response).

Do you know a way I could achieve this?

Thank you,

Aidan

**Comment by mefellows** [comment]
I think you would probably use _provider states_ to handle this case, and ensure the data fixtures for the provider are clearly setup before pact tests to be able to test each scenario.

Take a look at some of the docs at docs.pact.io about behavioural/functional tests.
